pipeline:
  identifier: Build_krrishkishore_jhttp_1720115160474
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: jhttp
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1677504810510
        repoName: krrishkishore/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI inside build_java_app"
                      mvn -B package --file pom.xml
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
