pipeline:
  identifier: Build_jhttp_1692865663194
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1677504810510
        repoName: krrishkishore/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn clean package dependency:copy-dependencies
              - step:
                  type: Run
                  name: check dependencies
                  identifier: check_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn dependency-check:check -U -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/target/*.xml
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
